FROM ghcr.io/project-copacetic/copacetic/debian:12-slim
RUN apt-get update \
    && apt-get install -y --no-install-recommends debconf perl libterm-readline-perl-perl \
    && rm -rf /var/lib/apt/lists/*
