name: "Experimental patch di Copacetic"

on:
  push:
    #branches:
    #  - "main"
  #schedule:
  #  - cron: "0 2 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to SIGHUP new Registry
        uses: docker/login-action@v1
        with:
          registry: registry.sighup.io
          username: ${{ secrets.SIGHUP_REGISTRY_USERNAME }}
          password: ${{ secrets.SIGHUP_REGISTRY_PASSWORD }}
      - name: Install trivy and copa
        run: |
          sudo apt-get install wget apt-transport-https gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
          trivy --version

          wget https://github.com/moby/buildkit/releases/download/v0.16.0/buildkit-v0.16.0.linux-amd64.tar.gz
          tar -xzvf buildkit-v0.16.0.linux-amd64.tar.gz -C /usr/local/bin/  --strip-components=1
          buildctl --version

          wget https://github.com/project-copacetic/copacetic/releases/download/v0.8.0/copa_0.8.0_linux_amd64.tar.gz
          tar -xzvf copa_0.8.0_linux_amd64.tar.gz
          chmod +x copa
          sudo mv copa /usr/local/bin/
          copa --version

      - name: Execute patch script
        run: |
          cd CVEs
          make patch

